export const property = {
  name: {
    label: "Name",
    key: "name",
    initialValue: "",
    info:"",
    page:1,
    required: true,
  },
  locality:{
    label: "Address Line 1",
    key: "locality",
    initialValue: "",
    info:"",
    page:3,
    required:true
  },
  street: {
    label: "Street",
    key: "street",
    initialValue: "",
    info:"",
    page:3,
    required: true,
  },
  city: {
    label: "City",
    key: "city",
    initialValue: "",
    info:"",
    page:3,
    required: true,
  },
  state: {
    label: "State",
    key: "state",
    initialValue: "",
    info:"",
    page:3,
    required: true,
  },
  zipCode: {
    label: "Zip Code",
    key: "zipCode",
    initialValue: "",
    info:"",
    page:3,
    required: true,
  },
  country: {
    label: "Country",
    key: "country",
    initialValue: "",
    info:"",
    page:3,
    required: true,
  },
  description: {
    label: "Description",
    key: "description",
    initialValue: "",
    info:"",
    page:4,
    required: true,
  },
  photos: {
    label: "Photos",
    key: "photos",
    initialValue: [],
    info:"",
    page:4,
    required: false,
  },
  category: {
    label: "Category",
    key: "category",
    initialValue: "",
    info:"",
    page:1,
    required: true,
  },
  listingType: {
    label: "Listing Type",
    key: "listingType",
    initialValue: "",
    info:"",
    page:1,
    required: true,
  },
  status: {
    label: "Status",
    key: "status",
    initialValue: "",
    info:"",
    page:1,
    required: true,
  },
  availability: {
    label: "Availability (days)",
    key: "availability",
    initialValue: "",
    info:"",
    page:1,
    required: true,
  },
  carpetArea: {
    label: "Area (sqft)",
    key: "carpetArea",
    initialValue: "",
    page:1,
    info:"Add Carpet Area for Apartment and Commercial Properties, for Condo and Houses add Total Property Area",
    required: true,
  },
  propertyAge:{
    label: "Property Age (in Yrs)",
    key: "propertyAge",
    initialValue: "",
    page:2,
    info:"Provide total years count from property was developed",
    required: true,
  },
  furnishing: {
    label: "Furnishing",
    key: "furnishing",
    initialValue: "",
    info:"",
    page:2,
    required: true,
  },
  price: {
    label: "Price (in Rs.)",
    key: "price",
    initialValue: "",
    info:"",
    page:1,
    required: true,
  },
  floor: {
    label: "Floor",
    key: "floor",
    initialValue: "",
    info:"",
    page:2,
    required: false,
  },
  facing: {
    label: "Facing",
    key: "facing",
    initialValue: "",
    info:"",
    page:2,
    required: false,
  },
  lift: {
    label: "Lift",
    key: "lift",
    initialValue: "",
    info:"",
    page:2,
    required: false,
  },
  bathroom: {
    label: "Bathrooms",
    key: "bathroom",
    initialValue: "",
    info:"",
    page:2,
    required: false,
  },
  bedroom: {
    label: "Bedrooms",
    key: "bed",
    initialValue: "",
    info:"",
    page:2,
    required: false,
  },
  balcony: {
    label: "Balcony",
    key: "balcony",
    initialValue: "",
    info:"",
    page:2,
    required: false,
  },
  parking: {
    label: "Parking (count)",
    key: "parking",
    initialValue: "",
    info:"",
    page:2,
    required: false,
  },
  waterAvailability: {
    label: "Water Availability",
    key: "waterAvailability",
    initialValue: "",
    info:"",
    page:2,
    required: false,
  },
  electricityAvailability: {
    label: "Electricity Availability",
    key: "electricityAvailability",
    initialValue: "",
    info:"",
    page:2,
    required: false,
  }
};

export const defaultPropertyData = Object.values(property).reduce(
  (acc, curr) => {
    const key = curr.key;
    const init = curr.initialValue;
    acc[key] = init;
    return acc;
  },
  {}
);

